#TODO: add pets model(s)
from pydantic import BaseModel, ValidationError
from .common import PetTypeEnum
from typing import Optional

# This model allows POST requests to come in without IDs, which
# would normally be generated by a database.
class PetBase(BaseModel):
    name: str
    breed: str
    petType: PetTypeEnum
    dob: str
    sterilized: bool
    user: str

# Using this class to facilitate the PATCH method.
# The targeted fields will be merged into the proper model
# while the empty fields are ignored.
class PetPartial(BaseModel):
    id: str
    name: Optional[str] = None
    breed: Optional[str] = None
    petType: Optional[PetTypeEnum] = None
    dob: Optional[str] = None
    sterilized: Optional[bool] = None
    user: Optional[str] = None

class PetCreate(PetBase):
    pass

class PetWithId(PetBase):
    id: str